"""messages: cascade FKs on sender_id / receiver_id

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-05-16 04:10:00.000000

Allow deleting a User row directly without hitting

    Key (id)=(...) is still referenced from table messages.

We drop the existing FKs on messages.sender_id and messages.receiver_id
and recreate them with ON DELETE CASCADE so chat rows are removed
alongside their owner. Names match the Postgres autogenerated defaults;
if your constraints were named differently (e.g. on a sqlite/dump-restored
DB), adjust the `op.drop_constraint` arguments below.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "e5f6a7b8c9d0"
down_revision: Union[str, None] = "d4e5f6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # sender_id ➜ users.id
    op.drop_constraint("messages_sender_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_sender_id_fkey",
        source_table="messages",
        referent_table="users",
        local_cols=["sender_id"],
        remote_cols=["id"],
        ondelete="CASCADE",
    )

    # receiver_id ➜ users.id
    op.drop_constraint("messages_receiver_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_receiver_id_fkey",
        source_table="messages",
        referent_table="users",
        local_cols=["receiver_id"],
        remote_cols=["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint("messages_receiver_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_receiver_id_fkey",
        source_table="messages",
        referent_table="users",
        local_cols=["receiver_id"],
        remote_cols=["id"],
    )

    op.drop_constraint("messages_sender_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_sender_id_fkey",
        source_table="messages",
        referent_table="users",
        local_cols=["sender_id"],
        remote_cols=["id"],
    )
